language: objective-c
before_install:
  - brew outdated xctool || brew upgrade xctool
xcode_workspace: CRToastDemo.xcworkspace
# xcode_project: CRToastDemo.xcodeproj
xcode_scheme: CRToastTests
xcode_sdk:
  - iphonesimulator8.1

before_install: gem install cocoapods slather -N
after_success: slather
